"use client";
import { useState, Suspense } from 'react';
import ActivityFeed from '../components/ActivityFeed';
import Leaderboard from '../components/Leaderboard';

function HomeContent() {
  const [url, setUrl] = useState('');

  return (
    <div className="max-w-6xl mx-auto w-full grid grid-cols-1 lg:grid-cols-3 gap-12 items-start relative z-10">
      
      {/* MAIN SECTION */}
      <div className="lg:col-span-2 space-y-12">
        <header className="space-y-4">
          <h1 className="text-7xl font-extralight tracking-tighter leading-none">
            <span className="text-trust">Trust</span>
            <span className="text-trace font-bold">Trace</span>
          </h1>
          <div className="space-y-1">
            <p className="text-2xl font-light text-slate-500 italic">Awareness before accountability.</p>
            <p className="text-lg font-light text-slate-400 tracking-tight">A decentralised mirror of consumer experiences.</p>
          </div>
        </header>

        {/* SEARCH BOX */}
        <div className="relative group">
          <input
            type="text"
            placeholder="Verify a digital entity (URL)..."
            className="w-full p-7 pl-9 rounded-[2.5rem] bg-white/70 dark:bg-slate-900/40 backdrop-blur-2xl border border-slate-200 dark:border-slate-800 shadow-xl outline-none focus:ring-8 focus:ring-blue-500/10 text-slate-900 dark:text-white text-xl font-light"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <button className="absolute right-3 top-3 bottom-3 px-10 rounded-3xl bg-slate-900 dark:bg-blue-600 text-white font-black text-xs uppercase tracking-widest transition-all">
            Verify
          </button>
        </div>

        <ActivityFeed />
      </div>

      {/* SIDEBAR SECTION */}
      <aside className="space-y-10 lg:sticky lg:top-12">
        <Leaderboard />
        
        {/* FIXED PHILOSOPHY CARD */}
        <div className="philosophy-card p-10 rounded-[3.5rem] shadow-2xl relative overflow-hidden">
          <h4 className="text-[10px] font-bold uppercase tracking-[0.4em] text-blue-400 mb-8">OUR PHILOSOPHY</h4>
          <p className="text-sm font-light leading-relaxed">
            TrustTrace uses <span className="font-medium text-white">Collective Intelligence</span> to protect consumers. Ratings are 100% generated by verified user experiences.
          </p>
          <div className="mt-8 pt-8 border-t border-white/10">
            <p className="text-5xl font-extralight tracking-tighter">2.4k</p>
            <p className="text-[10px] uppercase tracking-widest text-blue-400/60 mt-2">Scams Prevented</p>
          </div>
        </div>
      </aside>
    </div>
  );
}

export default function Home() {
  return (
    <main className="min-h-screen p-6 md:p-12 relative">
      {/* BACKGROUND ELEMENTS */}
      <div className="mesh-gradient">
        <div className="absolute top-[-10%] left-[-5%] w-[60%] h-[60%] bg-blue-100/40 dark:bg-blue-900/10 rounded-full blur-[160px]"></div>
        <div className="absolute bottom-[-10%] right-[-5%] w-[50%] h-[50%] bg-rose-100/20 dark:bg-rose-900/10 rounded-full blur-[140px]"></div>
      </div>
      
      <Suspense fallback={<div>Syncing...</div>}>
        <HomeContent />
      </Suspense>
    </main>
  );
};